name: 'Prose Linter'
description: 'Lint Docs website content using Vale'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: errata-ai/vale-action@reviewdog
      with:
        reporter: github-pr-check
        files: '["docs/pages]"'
        vale_flags: '--config=./docs/.vale.ini'
        fail_on_error: true
